DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 250
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  RRCROP_SCALE: (0.5, 1)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "adamw"
  LR: 0.001
  MAX_EPOCH: 50
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  MMRL:
    SCALE: 0.7
    REG_WEIGHT: 0.5
    N_REP_TOKENS: 5
    REP_LAYERS: [6, 7, 8, 9, 10, 11, 12]
    PREC: "amp"
    REP_DIM: 512